spring:
  profiles:
    active: h2

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO
    com:
      amor:
        api: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2 #h2 환경설정
  h2:
    console:
      enabled: true #h2 Console
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 100
    open-in-view: false

